name: Verify cached license metadata

on:
  # run on pushes to main
  push:
    branches:
      - main
  # run on all pull request events
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # run on demand
  workflow_dispatch:

jobs:
  licensed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    # setup action requirements
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - uses: ruby/setup-ruby@d781c1b4ed31764801bfae177617bb0446f5ef8d
      with:
        ruby-version: ruby

    # install and run this action
    - run: npm install --production --ignore-scripts
    - name: Run setup-licensed
      uses: ./
      with:
        version: '4.x'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # run licensed-ci to check and update licenses
    - uses: licensee/licensed-ci@98eef7c23bcf8211e108781a9594e969da913e89
      with:
        workflow: push_for_bots
        dependabot_skip: 'true'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cleanup_on_success: 'true'
